OWNERS
=> chore: add OWNERS

.gitignore, .yamllint, Makefile, build/Dockerfile, make/dev.mk, make/find-tools.mk, make/format.mk, make/git.mk, make/go.mk, make/help.mk, make/lint.mk, make/out.mk, make/test.mk, make/verbose.mk, openshift-ci/Dockerfile.deploy, openshift-ci/Dockerfile.tools
Introduce new make targets required for openshift-ci
=> chore: introduce make target required for openshift-ci

deploy/crds/toolchain_v1alpha1_nstemplateset.yaml, deploy/crds/toolchain_v1alpha1_useraccount.yaml
The same as https://github.com/codeready-toolchain/host-operator/pull/10
=> Rename CRD files to align with api generator

deploy/crds/toolchain_v1alpha1_useraccount.yaml, examples/toolchain_v1alpha1_useraccount_cr.yaml
We need **UserID** to create **Identity** and **UserIdentityMapping** resources.
=> Add UserID to UserAccount

make/format.mk, make/go.mk, make/out.mk, openshift-ci/Dockerfile.deploy
also, use `$(OUT_DIR)` whenever possible
=> chore: build binary under 'build' dir

openshift-ci/Dockerfile.tools
=> include 'jq' in CI tools

make/test.mk
=> upload coverage reports using OpenShift CI env vars

deploy/crds/toolchain_v1alpha1_useraccount.yaml
left over from this PR - https://github.com/codeready-toolchain/member-operator/pull/30
=> change due to api make genreate

deploy/operator_dev_cluster.yaml, make/deploy.mk, make/dev.mk
**Changes Proposed in this PR**
- Adds ImageStream which points to image from openshift CI cluster.
- Add DeploymentConfig which uses above ImageStream
- Fix minor make targets
=> add dev cluster deploymentconfig

make/test.mk, openshift-ci/Dockerfile.tools
*Changes Proposed in this PR*
* Add make target to deploy host-operator
* Add make target to create kubefedcluster cr
* install `jq` tool for k8s yaml parsing
=> add make target for deploy host and create kubefedcluster for e2e

openshift-ci/Dockerfile.tools
*Changes Proposed in this PR*
- Introduce go-bindata to generate go source code from yaml files.
- Separated this as due to this change, you can't build the source code https://github.com/codeready-toolchain/member-operator/pull/49/. you need this to be on master
=> introduce go-bindata in Dockerfile.tools

README.adoc, make/test.mk
same PR is this one https://github.com/codeready-toolchain/host-operator/pull/51
=> chore: print logs when e2e tests fail & change variable names

deploy/crds/toolchain_v1alpha1_useraccount.yaml
Result of CRD generated after https://github.com/codeready-toolchain/api/pull/28
=> preserve custom fields in CRDs

deploy/crds/toolchain_v1alpha1_useraccount.yaml
see https://github.com/codeready-toolchain/api/pull/30
=> fix JSONPath syntax for additionalPrinterColumns

cmd/manager/main.go, cmd/manager/main_test.go
=> add commit and buildtime vars

deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
=> update CRDs with extra annotations, generated with go 1.13

cmd/manager/main.go
Refactor the main function and add some comments describing what it is doing
=> chore: refactor main and add comments

.golangci.yml, make/lint.mk
=> configure golangci timeout

deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml, hack/deploy_csv.yaml
See https://github.com/codeready-toolchain/api/pull/51
=> Regenerate manifests by controller-runtime 0.2

README.adoc
...so we know that it's passing or failing :-)
=> chore: add CD status images

pkg/template/processor.go, pkg/template/processor_test.go
if the object to update can be cast to
'unstructured.Unstructured`, then use the client
to get the existing version before replacing it with
the given one.
Fixes CRT-288
=> set resourceversion before updating

deploy/cluster_role.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml, deploy/role.yaml, hack/deploy_csv.yaml
=> add missing permissions to serviceaccount

hack/deploy_csv.yaml, hack/install_operator.yaml
see https://github.com/codeready-toolchain/api/pull/67
=> chore: reflect changes in hack resource names

deploy/cluster_role.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml, hack/deploy_csv.yaml
Required for codeready-toolchain/host-operator#125
=> Add permissions to edit roles for operator SA

go.mod, go.sum
see https://github.com/codeready-toolchain/api/pull/82
=> chore: update api repo to use openshift/api@release-4.2

go.mod, go.sum, pkg/controller/useraccount/useraccount_controller.go, pkg/controller/useraccount/useraccount_controller_test.go
Updates the codeready-toolchain/api version and the reasons from codeready-toolchain/api in both controller and tests. relates to: https://github.com/codeready-toolchain/api/pull/86
=> Using reasons in api

deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml, hack/deploy_csv.yaml
=> add 'clusterResources' field in NSTemplateSet

deploy/cluster_role.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml, hack/deploy_csv.yaml
Required by https://github.com/codeready-toolchain/host-operator/pull/164
=> Add * permissions for NetworkPolicy to SA role

go.mod, go.sum, pkg/controller/nstemplateset/nstemplateset_controller.go
Follow-up of https://github.com/codeready-toolchain/toolchain-common/pull/96
=> chore: update to latest toolchain-common

pkg/controller/nstemplateset/nstemplateset_controller.go, pkg/controller/nstemplateset/nstemplateset_controller_test.go
While listing the existing ClusterResourceQuotas it was forgotten to use the ListOption for filtering by `owner` label. It shouldn't cause any issues, but it's better to use it and it makes the code more efficient.
=> fix: list ClusterResourceQuotas by owner label

deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml, hack/deploy_csv.yaml
Regenerated files from the api repository
Updates https://issues.redhat.com/browse/CRT-499
=> feat: add TierTemplate

go.mod, go.sum, pkg/controller/nstemplateset/nstemplateset_controller.go
a small simplification of the code
see https://github.com/codeready-toolchain/toolchain-common/pull/100
=> chore: let apply client take care of the labels assignment

deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_nstemplateset_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_useraccount_crd.yaml, go.mod, go.sum, hack/deploy_csv.yaml
Related PR: https://github.com/codeready-toolchain/api/pull/158
This PR contains generated files for the new `MemberStatus` resource + changes required for adding `lastUpdatedTime` to the condition.
=> Add member status resource

cmd/manager/main.go
There are some bug fixes & improvements in operator metrics introduced in operator-sdk 0.16.
See https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/#v016x
=> Bug Fixes and Improvements for Metrics

deploy/crds/toolchain_v1alpha1_toolchaincluster_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_toolchaincluster_crd.yaml, hack/deploy_csv.yaml
Adds ToolchainCluster CRD
result of https://github.com/codeready-toolchain/api/pull/172
=> chore: add ToolchainCluster CRD

pkg/controller/useraccount/useraccount_controller.go
=> add comment in case of UserAccount deletion

go.mod, go.sum
includes changes brought by https://github.com/codeready-toolchain/toolchain-common/pull/126
=> toolchain-common module update

deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml, hack/deploy_csv.yaml
Reflect changes in https://github.com/codeready-toolchain/api/pull/188
=> chore: add resource usage to MemberStatus & refactor ToolchainStatus

deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml, hack/deploy_csv.yaml
CRDs generated by codeready-toolchain/api#194
=> Add Console and Che URLs to member and toolchain status resources

deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/crds/toolchain_v1alpha1_toolchaincluster_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_toolchaincluster_crd.yaml, hack/deploy_csv.yaml
generated from https://github.com/codeready-toolchain/api/pull/196
=> chore: drop zones & region from ToolchainCluster

pkg/che/tokencache_test.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/memberstatus/memberstatus_controller_test.go
See https://github.com/codeready-toolchain/toolchain-infra/pull/42
=> Use CRW default namespace name

deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml, deploy/operator.yaml, hack/deploy_csv.yaml
Fixes https://issues.redhat.com/browse/CRT-786
=> operator resource requests and limits

deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml, deploy/operator.yaml, deploy/webhook/member-operator-webhook.yaml, hack/deploy_csv.yaml, pkg/webhook/deploy/deployment_test.go
There was a long thread with OpenShift folks regarding setting limits in OpenShift payloads. There were recommendations do not set them at all for most cases. Some of the reasons are defined there: https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
=> Drop operator limits

README.adoc
=> chore: add info about releases

go.mod, go.sum, pkg/controller/memberstatus/creation.go, pkg/controller/nstemplateset/cluster_resources.go, pkg/controller/nstemplateset/namespaces.go, pkg/webhook/deploy/deployment.go
=> update toolchain-common with new ApplyClient

pkg/controller/memberstatus/memberstatus_controller.go, pkg/controller/memberstatus/memberstatus_controller_test.go
Fixes https://issues.redhat.com/browse/CRT-953
Adds support for multi-role nodes.
=> CRT-953 support multiple roles for nodes

deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml, hack/deploy_csv.yaml
fixes wrt: https://issues.redhat.com/browse/CRT-971 - adding a new property apiEndpoint in MemberStatusStatus api
related PR: https://github.com/codeready-toolchain/api/pull/219
=> CRDs updated after adding a new property apiEndpoint in api

deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml, hack/deploy_csv.yaml
moving apiEndpoint from MemberStatusStatus to Member
fixes wrt: https://issues.redhat.com/browse/CRT-971 - 
related PR: https://github.com/codeready-toolchain/api/pull/221
=> CRDs updated for moving apiEndpoint to Member

pkg/controller/memberstatus/memberstatus_controller.go, pkg/controller/memberstatus/memberstatus_controller_test.go
https://issues.redhat.com/browse/OHSS-3322?focusedCommentId=15980402&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15980402
=> chore: ignore infra nodes when counting consumption

make/go.mk
Fixes - https://issues.redhat.com/browse/CRT-1041
This PR allows to identify underlying and build
corresponding binaries as require
Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>
=>  Add support for mutil-architecture

README.adoc, make/dev.mk
fix wrt to: https://issues.redhat.com/browse/CRT-904
=> remove minishift support from makefile and update readme

pkg/controller/idler/idler_controller.go, pkg/controller/idler/idler_controller_test.go, pkg/controller/memberstatus/memberstatus_controller.go, pkg/controller/memberstatus/memberstatus_controller_test.go, pkg/controller/useraccount/useraccount_controller.go, pkg/controller/useraccount/useraccount_controller_test.go, pkg/controller/useraccountstatus/useraccount_status_controller.go, pkg/controller/useraccountstatus/useraccount_status_controller_test.go
https://coreos.slack.com/archives/CHK0J6HT6/p1620732956300200
=> chore: rename controller types to Reconciler

go.mod, go.sum, pkg/controller/nstemplateset/nstemplateset_controller_test.go
Updating common & fixing test to match with the current version [(change introduced some time ago)](https://github.com/codeready-toolchain/toolchain-common/commit/5dd7ad1085b45e69e63fa71c1c656efcf88612b2)
Updating api as it hasn't been updated for a long time
=> fix: update common & api

go.mod, go.sum
This PR updates the API and toolchain-common dependencies to the latest version.
=> Update API and toolchain-common dependencies to latest versions

cmd/manager/main.go
modify scheme api initialization so it's closer to what is generated by operator-sdk
=> chore: modify scheme api initialization

deploy/crds/toolchain.dev.openshift.com_idlers.yaml, deploy/crds/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, deploy/crds/toolchain.dev.openshift.com_memberstatuses.yaml, deploy/crds/toolchain.dev.openshift.com_nstemplatesets.yaml, deploy/crds/toolchain.dev.openshift.com_toolchainclusters.yaml, deploy/crds/toolchain.dev.openshift.com_useraccounts.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_idlers.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_memberstatuses.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_nstemplatesets.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_toolchainclusters.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_useraccounts.yaml, hack/deploy_csv.yaml
result of: https://github.com/codeready-toolchain/api/pull/241
=> chore: update CRDs regenerated by binary directly

.github/workflows/publish-operators-for-e2e-tests.yml
=> chore: rename & update publish-operators-for-e2e-tests.yml to the latest

deploy/crds/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, deploy/olm-catalog/toolchain-member-operator/manifests/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, go.mod, go.sum, hack/deploy_csv.yaml
Generated files from https://github.com/codeready-toolchain/api/pull/246
=> Generated files for updated API

deploy/autoscaler/member-operator-autoscaler.yaml, pkg/autoscaler/autoscaler_test.go
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/331
=> Autoscaler buffer priority should be higher than autoscaler threshold

controllers/nstemplateset/nstemplateset_controller.go, controllers/nstemplateset/nstemplateset_controller_test.go
the controller is maybe not triggered when the Namespace is finally removed - let's requeue after 1 second every time when it's deleting a namespace.
=> fix: requeue after 1 second when deleting namespace

controllers/useraccount/useraccount_controller.go
add additional logging to try to figure out why UserAccount stays in updating state.
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/371
=> fix: add additional logging to fix UserAccount in updating state

deploy/env/dev.yaml, deploy/env/e2e-tests.yaml, deploy/env/prod.yaml
Related Issue: https://issues.redhat.com/browse/CRT-1176
Removes the old configuration files.
=> Remove old configuration files

config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Related API PR: https://github.com/codeready-toolchain/api/pull/258
Fixes https://issues.redhat.com/browse/CRT-1254
=> API Regeneration

config/crd/bases/toolchain.dev.openshift.com_nstemplatesets.yaml
=> refactor: update print columns

go.mod, go.sum, test/cluster.go
related PR https://github.com/codeready-toolchain/toolchain-common/pull/217
=> chore: update common dependency with cluster Config

controllers/idler/idler_controller.go
log fields with `.` are not super-friendly with LogQL.
=> refactor: improve log messages of idler

config/crd/bases/toolchain.dev.openshift.com_nstemplatesets.yaml, config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml, go.mod, go.sum
See also:
- https://github.com/codeready-toolchain/api/pull/284
- https://github.com/codeready-toolchain/toolchain-common/pull/227
Fixes https://issues.redhat.com/browse/CRT-1382
=> test: remove support for custom templates in NSTemplateSet

config/crd/bases/toolchain.dev.openshift.com_nstemplatesets.yaml, config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml, go.mod, go.sum
see https://github.com/codeready-toolchain/api/pull/285
Fixes https://issues.redhat.com/browse/CRT-1336
=> feat: SpaceRoles in NSTemplateSet 

controllers/nstemplateset/space_roles.go
=> refactor: handle JSON marshaling failures

go.mod, go.sum
include renaming of 'Member.APIEndpoint' field, but no change in code
was needed
=> chore: update api and toolchain-common dependencies

controllers/useraccount/useraccount_controller.go, controllers/useraccount/useraccount_controller_test.go
All resources created by sandbox should have the provider label populated for uniformity and easy identification of resources. fix wrt - https://issues.redhat.com/browse/CRT-1436
related e2e test - https://github.com/codeready-toolchain/toolchain-e2e/pull/474
This also unblocks the logic for https://github.com/codeready-toolchain/member-operator/pull/316. Although the webhook here could use the owner label instead, so it wasn't a hard block.
=> add provider label to user and identity

controllers/useraccount/useraccount_controller.go, controllers/useraccount/useraccount_controller_test.go, go.mod, go.sum
Set the email annotation at the `User` resource
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/476
=> feat: propagate email annotation to User resource

controllers/useraccount/useraccount_controller_test.go, go.mod, go.sum
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/485
=> Update toolchain-common dependency for userID encoding fix

controllers/useraccount/useraccount_controller_test.go
This PR simply adds a couple new unit tests for UserAccountControllers.
=> Added unit tests to cover missing error cases

.github/workflows/publish-operators-for-e2e-tests.yml
related pr: https://github.com/codeready-toolchain/toolchain-cicd/pull/53
=> fix(gh-actions): set gh-head-ref param

go.mod, go.sum
related PRs: 
* https://github.com/codeready-toolchain/api/pull/297
* https://github.com/codeready-toolchain/toolchain-common/pull/246
=> chore: update api & commont that drop syncIndex from MUR

controllers/nstemplateset/cluster_resources_test.go, controllers/nstemplateset/namespaces_test.go, controllers/nstemplateset/nstemplateset_controller_test.go, controllers/nstemplateset/status_test.go
Update namespace, role and rolebinding names to better reflect current prod templates
=> test: update NSTemplateSet controller test

controllers/nstemplateset/nstemplateset_controller.go
Required by https://github.com/codeready-toolchain/host-operator/pull/648
=> Add resourcequotas to operator SA role

config/crd/bases/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, controllers/memberoperatorconfig/configuration.go, controllers/memberoperatorconfig/configuration_test.go, controllers/useraccount/useraccount_controller.go, controllers/useraccount/useraccount_controller_test.go, go.mod, go.sum
Generated files for https://github.com/codeready-toolchain/api/pull/314
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/571
=> Add SkipUserCreation config to control User and Identity creation

cmd/webhook/main.go, controllers/memberstatus/creation.go, controllers/memberstatus/creation_test.go, controllers/nstemplateset/client.go, controllers/nstemplateset/client_test.go, go.mod, go.sum, main.go, pkg/autoscaler/autoscaler.go, pkg/webhook/deploy/deployment.go
=> refactor: no need for runtime.Scheme in ApplyClient

controllers/idler/idler_controller.go, controllers/idler/idler_controller_test.go
The replicas field defined in specReplicasPath may be optional in the custom resource. In this case getting the scale resource fails with internal server error. In this case try to set a new scale resource with replicas=0. This fixes idling of Camel K integrations and bindings that do not explicitly have a `spec.replicas` field set and default to replicas=1.
Signed-off-by: Christoph Deppisch <cdeppisch@redhat.com>
=> fix(#343): Support scale resources that do not have specReplicasPath field set

.github/workflows/ci-build.yml
print the generated JSON file in the console for now
=> build: run CycloneDX action to generate SBOM

PROJECT, config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml, config/crd/kustomization.yaml, config/manifests/bases/member-operator.clusterserviceversion.yaml, go.mod, go.sum, make/run-cicd-script.mk
Add SpaceRequest CRD
Jira Ticket: [ASC-244](https://issues.redhat.com/browse/ASC-244)
Related PRs:
- api: https://github.com/codeready-toolchain/api/pull/333
- sandbox-sre: https://github.com/codeready-toolchain/sandbox-sre/pull/874
- toolchain-cicd: https://github.com/codeready-toolchain/toolchain-cicd/pull/78
=> ASC-224 add space request

controllers/nstemplateset/nstemplateset_controller.go
needed for the `appstudio` tier
see also https://github.com/codeready-toolchain/host-operator/pull/735
=> feat: grant permission to on environments.appstudio.redhat.com

PROJECT, config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml, config/crd/kustomization.yaml, config/manifests/bases/member-operator.clusterserviceversion.yaml
Paired with https://github.com/codeready-toolchain/api/pull/337
=> Generated files for workspace api

config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml
Related PR: https://github.com/codeready-toolchain/api/pull/340
=> Generated files after adding workspace type

controllers/idler/idler_controller.go, controllers/idler/idler_controller_test.go, go.mod, go.sum, pkg/che/che.go, pkg/che/tokencache.go, test/idler_assertion.go
no need to report an error, since timeout=0 is valid for '___noidling' tiers
see also:
- https://github.com/codeready-toolchain/api/pull/349
- discussion on [Slack#forum-dev-sandbox](https://redhat-internal.slack.com/archives/CHK0J6HT6/p1677582613636039)
=> refactor: skip idling when timeout is 0

config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml, go.mod, go.sum
retrieve 'Tier' from label, include 'Created_at' and remove 'NS_Limit'
see https://github.com/codeready-toolchain/api/pull/352
=> fix useraccount printcolumns

make/webconsole.mk, webconsole_source/Containerfile, webconsole_source/package.json
also, use '/opt/app-root' as the base work directory
=> chore(webconsole): build assets with ubi8/nodejs-16

config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Ref. https://issues.redhat.com/browse/RHTAPBUGS-281
=> Allow ECP access to appstudio-pipelines-runner

go.mod, main.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
Similar to https://github.com/codeready-toolchain/host-operator/pull/815
See also https://github.com/codeready-toolchain/toolchain-e2e/pull/744
=> feat(metrics): add metric for deployed version

config/crd/bases/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, go.mod, go.sum
Jira: https://issues.redhat.com/browse/SANDBOX-53
Related to:
- https://github.com/codeready-toolchain/api/pull/362
=> feat: add environment field to memberoperator config

config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Removing accesses connected with sharedSecrets which are not used anymore.
=> STONEBLD-1320: reduce permissions for rhtap pipeline SA

pkg/webhook/mutatingwebhook/mutate.go, pkg/webhook/validatingwebhook/validate_checluster_request.go, pkg/webhook/validatingwebhook/validate_rolebinding_request.go
fix wrt: https://issues.redhat.com/browse/SANDBOX-78
=> use WriteString

pkg/webhook/mutatingwebhook/mutate.go, pkg/webhook/validatingwebhook/validate_checluster_request.go, pkg/webhook/validatingwebhook/validate_rolebinding_request.go
fix wrt : https://issues.redhat.com/browse/SANDBOX-78
=> do not pass the error to response body

pkg/webhook/validatingwebhook/validate_checluster_request.go, pkg/webhook/validatingwebhook/validate_rolebinding_request.go
for https://app.snyk.io/org/red-hat-developer-sandbox/project/dea17a29-8402-448b-ba92-11ca57f6c572#issue-37d47aaf-ea60-4557-94fd-628b86c44caf using https://pkg.go.dev/html#EscapeString
fix wrt: https://issues.redhat.com/browse/SANDBOX-78 - please find more details in the story.
=> escape string

controllers/memberoperatorconfig/memberoperatorconfig_controller.go
see: https://redhat-internal.slack.com/archives/CHK0J6HT6/p1690446745059439
=> fix: remove generation predicate from secrets watcher

PROJECT, config/crd/bases/toolchain.dev.openshift.com_spacebindingrequests.yaml, config/crd/kustomization.yaml, config/manifests/bases/member-operator.clusterserviceversion.yaml, go.mod, go.sum
This PR add a new API type SpaceBindingRequest, which will allow admin users to manage permissions on their own Space, and grant access to other users.
Jira: https://issues.redhat.com/browse/ASC-394
Related PRs:
- https://github.com/codeready-toolchain/api/pull/370
=> feat: add spacebindingrequest type

config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Regenerated from API, related PR: https://github.com/codeready-toolchain/api/pull/373
=> added PropagatedClaims to UserAccount type

config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Regenerated from API
PR: https://github.com/codeready-toolchain/api/pull/376
=> Added email address to propagated claims

controllers/idler/idler_controller_test.go, go.mod, go.sum
depends on https://github.com/codeready-toolchain/toolchain-common/pull/326
=> update to support list of emails

config/manager/manager.yaml
=> update kube-rbac-proxy to v4.13.0

make/test.mk
Same change as: https://github.com/codeready-toolchain/host-operator/pull/887
=> get pr branch name from CLONEREFS_OPTIONS

controllers/memberoperatorconfig/memberoperatorconfig_controller.go, controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go, pkg/autoscaler/autoscaler.go, pkg/autoscaler/autoscaler_test.go, pkg/cert/secret.go, pkg/cert/secret_test.go, pkg/utils/route/route.go, pkg/utils/route/route_test.go, pkg/webhook/deploy/deployment.go, pkg/webhook/deploy/deployment_test.go
=> fix: forward context into pkgs

controllers/nstemplateset/client.go, controllers/nstemplateset/client_test.go, controllers/nstemplateset/cluster_resources.go, controllers/nstemplateset/cluster_resources_test.go, controllers/nstemplateset/namespaces.go, controllers/nstemplateset/namespaces_test.go, controllers/nstemplateset/nstemplateset_controller.go, controllers/nstemplateset/nstemplatetier.go, controllers/nstemplateset/nstemplatetier_test.go, controllers/nstemplateset/space_roles.go, controllers/nstemplateset/space_roles_test.go, controllers/nstemplateset/status.go, controllers/nstemplateset/status_test.go
=> fix: forward context in NSTemplateSet reconciler

controllers/memberstatus/memberstatus_controller.go
=> fix: forward context in memberstatus reconciler

controllers/idler/idler_controller.go
=> fix: forward context in idler reconciler

config/manager/manager.yaml
=> upgrade ose-kube-rbac-proxy to v4.14

config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml, webconsole_source/yarn.lock
API PR: https://github.com/codeready-toolchain/api/pull/395
=> Regenerated from API changes

config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
API PR: https://github.com/codeready-toolchain/api/pull/398
=> Regenerated from API

.github/workflows/publish-operators-for-e2e-tests.yml
https://github.com/codeready-toolchain/registration-service/pull/394
=>  check substrings of GH comments to run PR CD workflow

.gitignore, webconsole_source/yarn.lock
`webconsole_source/yarn.lock` updated via `yarn upgrade`
=> webconsole: upgrade NPM modules

.github/dependabot.yml, .github/workflows/ci-build.yml, .github/workflows/operator-cd.yml, .github/workflows/publish-operators-for-e2e-tests.yml, .golangci.yml, controllers/idler/idler_controller_test.go, controllers/memberoperatorconfig/mapper_test.go, controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go, controllers/memberstatus/creation_test.go, controllers/nstemplateset/cluster_resources_test.go, controllers/nstemplateset/namespaces_test.go, controllers/nstemplateset/nstemplatetier_test.go, controllers/nstemplateset/space_roles_test.go, pkg/autoscaler/autoscaler_test.go, pkg/metrics/metrics_test.go, pkg/webhook/mutatingwebhook/userpods_mutate_test.go, pkg/webhook/validatingwebhook/validate_rolebinding_request_test.go, pkg/webhook/validatingwebhook/validate_ssp_request_test.go, test/namespace_assertion.go, test/nstemplateset_assertion.go
see docs at https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
see https://github.com/codeready-toolchain/sandbox-sre/pull/1578
=> chore: keeping our GitHub Actions up to date with Dependabot

deploy/toolchaincluster/member-sa.yaml
The manifest is not used yet, but I've missed the service account in the previous PR https://github.com/codeready-toolchain/member-operator/pull/537
=> add missing service account resource 

controllers/nstemplateset/client_test.go, controllers/nstemplateset/cluster_resources_test.go, controllers/nstemplateset/namespaces_test.go, controllers/nstemplateset/space_roles_test.go, controllers/nstemplateset/status_test.go, pkg/autoscaler/autoscaler.go
This PR cleans up the packages being imported more than once.
=> clean up packages being imported more than once

go.mod, go.sum
Test changes to the ApplyObject function in common client
The PR will be used to bump the toolchain-common version one this one is merged https://github.com/codeready-toolchain/toolchain-common/pull/373
=> bump toolchain-common version

cmd/webhook/main.go
fix for https://redhat-internal.slack.com/archives/CHK0J6HT6/p1717497882454029
=> reload member cache in webhook

go.mod, go.sum, main.go
This is just updating the toolchain-common dependency 
Related PR
- Toolchain-Common - https://github.com/codeready-toolchain/toolchain-common/pull/401
- Paired E2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1006
Related PR where only change is updating the dependency
- Host-opertor - https://github.com/codeready-toolchain/host-operator/pull/1049
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/437
- Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1000
- Sandbox-SRE - https://github.com/codeready-toolchain/sandbox-sre/pull/1830
- KSCTL - https://github.com/kubesaw/ksctl/pull/42
=> KUBESAW-100: Refactor tc-toolchaincluster controller

make/go.mk
This is related to the discussion 
https://github.com/codeready-toolchain/api/pull/437#discussion_r1691463409
=> add genereate-asset to mkfile target of verify

go.mod, go.sum
Part of https://issues.redhat.com/browse/SANDBOX-724
=> Update api and common

controllers/idler/idler_controller.go, controllers/idler/idler_controller_test.go
Use 1/12th of the configured idler timeout for VMs
=> Shorter VM idling

go.mod, go.sum
https://github.com/codeready-toolchain/toolchain-common/pull/462
=> fix: panic when GH api returns an error

controllers/idler/idler_controller.go, controllers/idler/idler_controller_test.go
if the predicate allows reconciliation based on the set startTime, but the client cache is not updated with the change, then the pod won't be tracked and the next reconciliation won't be scheduled based on the age of the pod. 
To avoid this problem, let's force the next reconciliation:
* to the idler timeout if the pod that lacks the starttime is non-VM pod
* to the 1/12th of the idler timeout if the pod that lacks the starttime is a VM pod
[SANDBOX-1023](https://issues.redhat.com/browse/SANDBOX-1023)
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1741610661596739
=> force idler reconcile

config/crd/bases/toolchain.dev.openshift.com_idlers.yaml, config/crd/bases/toolchain.dev.openshift.com_memberoperatorconfigs.yaml, config/crd/bases/toolchain.dev.openshift.com_memberstatuses.yaml, config/crd/bases/toolchain.dev.openshift.com_nstemplatesets.yaml, config/crd/bases/toolchain.dev.openshift.com_spacebindingrequests.yaml, config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml, config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml, config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml, config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml
Generated by https://github.com/codeready-toolchain/api/pull/462
[SANDBOX-808](https://issues.redhat.com/browse/SANDBOX-808)
=> SANDBOX-808: update controller-gen.kubebuilder.io/version to v0.15.0

controllers/idler/idler_controller.go, controllers/idler/mapper.go, controllers/idler/predicate.go, controllers/idler/predicate_test.go
* use typed predicate & mapper
* allow delete events only for users pods (with the users priority class name)
=> improve idler predicate & mapper

controllers/idler/aap_idler_test.go, controllers/idler/idler_controller_test.go
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1743169699845159?thread_ts=1743166514.789429&cid=CHK0J6HT6
* fix the VM start times to avoid flakiness
* increase the idler timeout to 3 hours (to have something more real, but the current logic should work with any value)
* use common assertion logic for verifying the delta in which the returned requeue time should be
* increase the delta to 10 seconds for cases when it takes more time to execute the test
=> idler: fix flaky unit tests

controllers/idler/aap_idler_test.go, controllers/idler/owners.go, controllers/idler/owners_test.go
https://redhat-internal.slack.com/archives/C07UWTB1BPB/p1747674594212969
https://issues.redhat.com/browse/SANDBOX-1183
=> fix: support non-controller owners
