codeready-toolchain/member-operator

- openshift-ci/Dockerfile.tools
Initially I tried to remove `dep` as we already moved to go modules. but looks like to install operator-sdk, we still need dep to be installed.
You can find failed build logs at https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/4034/rehearse-4034-pull-ci-codeready-toolchain-member-operator-master-test/2
> install dep as required for operator-sdk

- Makefile
- make/lint.mk
- make/test.mk
- openshift-ci/Dockerfile.tools
*Changes proposed in this PR*
- removes not-exist make target `/vendor`
- install operator-sdk by curl
- reduce number of caching layer by adding `LABEL` and `ENV` in single dir.
- exporting  `GO111MODULE=on`
> chore: fix make targets and install operator-sdk by curl

- openshift-ci/Dockerfile.tools
openshift CI failing to use build using git source strategy. 
Logs 
- https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/4034/rehearse-4034-pull-ci-codeready-toolchain-member-operator-master-lint/4/build-log.txt
- http://pastebin.test.redhat.com/771467
> move author under another LABEL instruction

- openshift-ci/Dockerfile.tools
Looks like build is failing as missing keyserver. You can find build logs at https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/4034/rehearse-4034-pull-ci-codeready-toolchain-member-operator-master-build/7/build-log.txt
However you can find documentation about how can you configure keyserver for operator-sdk https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md#verify-the-downloaded-release-binary
> chore: add keyserver to import gpg keys

- make/find-tools.mk
We don't need to verify that `dep` is installed or not as we are using `mod`. this is why removing it.
> chore: remove dep from require executables

- openshift-ci/Dockerfile.tools
*Changes Proposed in this PR*
- Change `GOCACHE` to `/tmp/.cache` directory where we have permission to create it.
CI build is failing - https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/4034/rehearse-4034-pull-ci-codeready-toolchain-member-operator-master-build/9/build-log.txt
> change GOCACHE under /tmp/.cache

- make/lint.mk
Build is failing https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/4034/rehearse-4034-pull-ci-codeready-toolchain-member-operator-master-lint/10/build-log.txt
> download golangci-lint using go get

- openshift-ci/Dockerfile.deploy
Currently we are trying to use same dockerfile for local development and ci setup. But looks like CI setup is expecting it only `operator` not `out/operator` as it's copied from `bin` container
> change operator location as it's copied from bin container

- build/Dockerfile
- build/bin/entrypoint
- build/bin/user_setup
If we try to build operator using `operator-sdk build quay.io/codeready-toolchain/member-operator`, then it's failing due to symbolic link and missing `bin` directory
> revert Dockerfile as symbolic link is not working for operator-sdk build

- deploy/role.yaml
add toolchain.dev.openshift.com group to member-operator role so the ServiceAccount can watch these CRs
> fix: add toolchain.dev.openshift.com group to member-operator role

- .codecov.yaml
- .yamllint
- Makefile
- README.adoc
- make/clean.mk
- make/dev.mk
- make/find-tools.mk
- make/format.mk
- make/git.mk
- make/go.mk
- make/help.mk
- make/lint.mk
- make/out.mk
- make/test.mk
- make/verbose.mk
- remove all 'inlclude' directives and just
use a wildcard include in Makefile
- add coverage on 'test' and upload the result
to codecov.io with the token for the repo
- add a goal to run the tests (except E2E) without
coverage (aimed at local testing)
> reorg makefiles and setup codecov

- go.mod
- go.sum
- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccount/useraccount_controller_test.go
We currently "crate" `IdentityMapping`. Which is a virtual resource. The mapping rest endpoint modifies the corresponding User & Identity when the mapping is "created". It causes two reconciles in UserAccount controller which happen in parallel:
- **T1.** UserAcc created.
- **T2**. Reconcile 1 triggered. Create User. Exit Reconcile.
- **T3.** Reconcile 2. Create Identity. Exit.
- **T4.** Reconcile 3. "Create" Mapping (it modifies User and Identity, so it triggers two reconciles!). Exit reconcile.
- **T5-T6.** Race condition. Two reconciles (one because Identity modified and one because User modified)
This PR drops any `UserIdentityMapping` REST API usage. We now handle user & identity updates (for establishing a mapping between them) explicitly from the controller.
> Fix race condition in UserAccount controller

- deploy/crds/toolchain_v1alpha1_useraccount.yaml
- go.mod
- go.sum
- make/clean.mk
- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccount/useraccount_controller_test.go
- test/e2e/useraccount_test.go
- test/e2e/wait_util.go
This PR introduces Status Condition to UserAccount Controller: **Ready**
Also there are new [additional printer columns](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns) in UserAccount CRD:
```
$ oc get useraccounts
NAME        NS LIMIT   TIER NAME   READY     REASON 
bob         default    basic       True      Provisioned   
alice       default    basic       False     Provisioning   
johnsmith   admin      basic       False     UnableToCreateIdentity   
$ oc get useraccounts -o wide
NAME        USER ID               NS LIMIT   TIER NAME   READY     REASON                    DISABLED
bob         d8a88d7-1d27c0d7e52   default    basic       True      Provisioned   
alice       f758563-2d27c0d7e53   default …
```
> Switch UserAccount to Status Conditions

- make/test.mk
* add make target to easily delete all namespaces that were created by e2e tests
* add automatic deletion of namespaces after e2e test
* add a new target that skips deletion of namespaces after e2e test
> feat: add/modify make targets to clean e2e namespaces

- deploy/cluster_role.yaml
- deploy/cluster_role_binding.yaml
- deploy/operator.yaml
- deploy/operator_dev_cluster.yaml
- deploy/role.yaml
- go.mod
- go.sum
- make/dev.mk
- make/test.mk
- pkg/config/constants.go
- pkg/config/env.go
- pkg/controller/kubefedcluster.go
- pkg/controller/useraccount/useraccount_controller.go
* separates Role and ClusterRole permissions
* modifies KubeFedCluster e2e test to meet changes in codeready-toolchain/toolchain-common#33
* removed unnecessary `OPERATOR_NAMESPACE` var
NOTE: depends on changes made in codeready-toolchain/toolchain-common#33 as well as in https://github.com/codeready-toolchain/host-operator/pull/55
> fix(CRT-223): separate Role and ClusterRole permissions + test fixes & adjustments

- go.mod
the git.apache.org seems to be still down https://status.apache.org/incidents/63030p4241xj
so I'm adding permanent workaround/solution
> chore: replace git.apache.org/thrift.git by github.com/apache/thrift

- make/test.mk
When the e2e tests are being executed in openshift-ci, then the repo will provide to e2e test logic the image that was already built for the member-operator PR
see codeready-toolchain/toolchain-e2e#6
> chore: when running in CI use built image in e2e tests

- make/test.mk
- openshift-ci/Dockerfile.tools
install newer git and allow unrelated histories while merging to avoid conflict while merging
> chore: install newer git and allow unrelated histories while merging

- .codecov.yaml
- make/test.mk
We can't really test cmd/manager properly in unit tests (it's coverd in e2e tests) so excluding it from the codecov report. See #73
> Exclude cmd/manager (main) from coverage report

- make/go.mk
Fixing invalid path in ldflag variable :/
> update Commit and BuildTime ldflags to new pkg path (fix)

- openshift-ci/Dockerfile.tools
to unblock e2e tests executed in member-operator repo: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/codeready-toolchain_member-operator/89/pull-ci-codeready-toolchain-member-operator-master-e2e/368
> fix(e2e): install gcc in Dockerfile.tools

- .travis.yml
- make/docker.mk
- make/find-tools.mk
brings travis config file that will for every commit to master branch:
* build the project
* build the image of the project and push it to quay
* using the olm scripts from `api` repo generate a new version of the host-operator and (using operator courier) pushes it to quay
Already working build can be seen here: https://travis-ci.org/MatousJobanek/member-operator
and the pushed bundles here: https://quay.io/application/matousjobanek/toolchain-member-operator?tab=releases
This PR depends on logic introduced in this PR https://github.com/codeready-toolchain/api/pull/58
IMPORTANT: This PR is ready to review, but please, don't merge it yet as I need to do some additional setup (in quay and in travis) just before merging it ;-)
> (DO NOT MERGE) chore: deploy csv for every commit in master via travis-ci

- deploy/cluster_role.yaml
- deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
- deploy/role.yaml
- hack/deploy_csv.yaml
There are a lot of error messages in the log:
```
cannot get resource "nodes" in API group "" in the namespace "toolchain-member-operator"
cannot list resource "roles" in API group "authorization.openshift.io"
cannot list resource "roles" in API group "rbac.authorization.k8s.io"
cannot list resource "componentstatuses" in API group ""
```
> Add missing Permissions to member operator SA

- deploy/cluster_role.yaml
- deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
- hack/deploy_csv.yaml
Fixes one more error I found in the logs:
```
E0102 14:41:22.330962       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *unstructured.Unstructured: processedtemplates.template.openshift.io is forbidden: User "system:serviceaccount:toolchain-member-operator:member-operator" cannot list resource "processedtemplates" in API group "template.openshift.io" in the namespace "toolchain-member-operator"
```
> Permission error in member

- cmd/manager/main.go
When creating metrics of our CRs we should use our toolchain apis 
This will get rid of the annoying errors `reflector.go:95: Failed to list` in the logs
> fix: use toolchain apis for listing CRs to be monitored

- go.mod
- go.sum
- pkg/apis/apis.go
The scheme should contain only CRs apis - this will get rid of the last `reflector.go:95: Failed to list` errors from our logs - we should create metrics for the extensions
see: https://github.com/codeready-toolchain/api/pull/83
> fix: common api sheme contain only CRs

- deploy/cluster_role.yaml
- deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
- deploy/role.yaml
- hack/deploy_csv.yaml
Since the RBAC issue with `reflector.go:95: Failed to list` errors should be fixed I decided to remove unneeded permissions from our roles. I didn't spend much time investigating which particular permissions are used and which are not, I just removed those that were apparently added just as a workaround for making our logs clean and happy.
> chore: remove unneeded permissons

- go.mod
- go.sum
- pkg/controller/nstemplateset/nstemplateset_controller.go
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
`owner` -> `toolchain.dev.openshift.com/owner`
`type` -> `toolchain.dev.openshift.com/type`
`revision` -> `toolchain.dev.openshift.com/revision`
Requires https://github.com/codeready-toolchain/api/pull/85
E2E tests - https://github.com/codeready-toolchain/toolchain-e2e/pull/64
> Add `toolchain.dev.openshift.com/` prefix to namespace labels

- .travis.yml
- openshift-ci/Dockerfile.tools
`yq` binary is needed in the script introduced here codeready-toolchain/api#88. The script will be then used for e2e tests as well as for CD
> chore: install github.com/kislyuk/yq binary

- go.mod
- go.sum
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
this PR fixes a few things in the test:
* there was a wrong indentation in the ClusterResourceQuotas yaml snipets
* when using fake client it should rely on changes of the generation - based on this information it decides what to do next
* ~the basic tier should contain the ClusterResourceQuotas resource - it's more or less prerequisite of all tiers~
* when creating the ClusterResourceQuotas resource during the test setup, we need to parse the quota from yaml file, otherwise, the object contains slightly different formating that the one retrieved from the template - this causes that it looks like the resource was modified, thus generation incremented
> fix: NSTemplateSet tests should test a CRQ in basic tier

- pkg/controller/nstemplateset/nstemplateset_controller.go
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
- test/nstemplateset_assertion.go
The PR improves the status handling in NSTemplateSet controller. First of all, it removes the message from the provisioning condition. The reasons are:
* there is no point in having the message - it doesn't bring any value
* it adds additional load in the status synchronization between UA and MUR
Then it changes methods:
* `setStatusProvisioning` -> `setStatusProvisioningIfNotUpdating`
* `setStatusUpdating` -> `setStatusUpdatingIfNotProvisioning`
so they first check if the other condition reason is set or not. If it's set, then keeps the original reason, if not, then sets the given reason. 
The reason for this change was that the conditions changed over and over agin from updating to provisioning and back.
> chore: improve status handling in NSTemplateSet controller

- go.mod
- go.sum
Include the `TemplateRef` field in the MUR, so it's not lost when the member operator sets the `SyncIndex` in the MUR on the host-operator once provisioning is complete.
Updates https://issues.redhat.com/browse/CRT-500
Signed-off-by: Xavier Coulon xcoulon@redhat.com
> chore: update to latest api

- go.mod
- pkg/controller/nstemplateset/cluster_resources.go
- pkg/controller/nstemplateset/cluster_resources_test.go
- pkg/controller/nstemplateset/namespaces.go
- pkg/controller/nstemplateset/namespaces_test.go
- pkg/controller/nstemplateset/nstemplateset_controller.go
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
- pkg/controller/nstemplateset/status.go
- pkg/controller/nstemplateset/status_test.go
- test/cluster_assertion.go
- test/nstemplateset_assertion.go
Since the NSTemplateSet controller (and mainly the associated test) was getting bigger and bigger and thus also cluttered I decided to split it into several files. As part of this effort, I created additional types to isolate the behavior for easier testing. One of the new types is `apiClient` that contains information for communication through the API and is used in all other types via composition.
* `cluster_resources.go` - takes care of creating, updating, and deleting of cluster resources contained in the respective template. The main entity is `clusterResourcesManager`.
* `namespaces.go` - takes care of creating, updating, and deleting of namespaces and its inner resources. The main entity is `namespacesManager`.
* `status.go` - takes care of updating NSTemplateSet.status. The main …
> chore: split nstemplateset controller

- deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml
- deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
- deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml
- deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml
- go.mod
- go.sum
- hack/deploy_csv.yaml
- pkg/controller/nstemplateset/cluster_resources.go
- pkg/controller/nstemplateset/cluster_resources_test.go
- pkg/controller/nstemplateset/namespaces.go
- pkg/controller/nstemplateset/namespaces_test.go
- pkg/controller/nstemplateset/nstemplateset_controller.go
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
- pkg/controller/nstemplateset/nstemplatetier.go
- pkg/controller/nstemplateset/nstemplatetier_test.go
- pkg/controller/nstemplateset/status_test.go
- pkg/controller/useraccount/useraccount_controller_test.go
- test/nstemplateset_assertion.go
This PR migrates the member-operator logic to the templateRef ield in NSTemplateSet. It stops using the legacy ones. 
In additon, it replaces both labels `/tier` and `/revision` with a new one `/templateref`
api PR: https://github.com/codeready-toolchain/api/pull/136
paired PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/110
>  feat(CRT-501): migrate NSTemplateSet to templateRef field 

- pkg/controller/nstemplateset/nstemplatetier.go
- pkg/controller/nstemplateset/nstemplatetier_test.go
Jira issue: https://issues.redhat.com/browse/CRT-660
Currently, when an NSTemplateSet contains TemplateRef that is empty then it returns `nil` for the `tierTemplate` parameter as well as for the `error` - it should return an error instead.
> fix: when templateRef is empty, then return an error

- go.mod
- go.sum
- pkg/controller/nstemplateset/cluster_resources.go
- pkg/controller/nstemplateset/nstemplatetier.go
Use constant containing ClusterResources template type name that was moved to the api repo.
depends on: https://github.com/codeready-toolchain/api/pull/140
> chore: move constant containing clusterresources type name to api

- pkg/controller/nstemplateset/cluster_resources.go
- pkg/controller/nstemplateset/cluster_resources_test.go
- pkg/controller/nstemplateset/namespaces.go
- pkg/controller/nstemplateset/namespaces_test.go
- pkg/controller/nstemplateset/nstemplateset_controller.go
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
- pkg/controller/nstemplateset/nstemplatetier.go
- pkg/controller/nstemplateset/nstemplatetier_test.go
- pkg/controller/useraccountstatus/useraccount_status_controller_test.go
- test/cluster.go
This is kind of follow-up of the fix from https://github.com/codeready-toolchain/member-operator/commit/1ab8fac311d1fc6ee43c945e897e770d3640a421
This PR changes the way the controller (and managers) retrieve the `TierTemplate` from the host-cluster. Now it calls the `getTierTemplate` function directly (instead of calling via another mockable function) by passing the `cluster.GetHostCluster` function. With this change we are able to properly test the error cases in the whole flow of the reconcile loop. 
In addition, it will help us also with testing the cache functionality that will come in the next PR (I just thought that it would be better to provide smaller PRs with fewer changes in the code)
To be honest, I wanted to change this way of mocking a long time ago, I just haven't had a …
> chore: call getTierTemplate function directly

- pkg/controller/nstemplateset/nstemplateset_controller_test.go
- pkg/controller/nstemplateset/nstemplatetier.go
- pkg/controller/nstemplateset/nstemplatetier_test.go
This PR adds a cache for TierTemplates retrieved from the host cluster. When a TierTemplate is retrieved from the host cluster, then it's stored in a map indexed by its name and for all future calls it uses only the cache instead of calling the host cluster again.
> feat: cache TierTemplates retrieved from the host cluster

- deploy/olm-catalog/toolchain-member-operator/bundle.Dockerfile
- deploy/olm-catalog/toolchain-member-operator/metadata/annotations.yaml
Adds two files needed by opm and by operator registry.
* `bundle.Dockerfile` used for the operator bundle image
* `metadata/annotations.yaml` containing metadata info about the operator bundle
> chore: add bundle metadata and Dockerfile

- .gitignore
- make/manifests.mk
Add new targets to manifests makefile - these targets will be used by CD to release a new nightly/staging releases.
* generate-cd-release-manifests - generates a new version of operator manifests
* push-manifests-as-app - pushes manifests as an application to quay
* push-bundle-and-index-image - pushes manifests as a bundle image to quay and adds it to the index image
* recover-operator-dir - recovers the operator bundle directory from backup folder
it also adds `tmp/` folder to gitignore
> chore: add manifests that will be used by CD

- cmd/manager/main.go
When getting the metrics, we have to use the schema builder taken from the api repo. The reason is that the schema builder adds only our toolchain CRDs + KubeFed api. The schema builder in host operator adds api also for additional groups and our ServiceAccount doesn't have enough permissions to list all of them. That's why we have a lot of `Failed to list *unstructured.Unstructured:` errors in our logs nowadays.
> fix: get metrics only for Toolchain CRDs

- cmd/manager/main.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/controller/controller.go
- pkg/controller/memberstatus/creation.go
- pkg/controller/memberstatus/creation_test.go
- pkg/controller/memberstatus/memberstatus_assertion.go
- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
- test/cluster.go
- test/memberstatus_assertion.go
Related issue: https://issues.redhat.com/browse/CRT-667
Link to PR tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/128
This PR adds a controller for the new MemberStatus resource. Its responsibility is to read the state of toolchain member cluster components and update the MemberStatus resource with information useful for observation or troubleshooting. For more details about the MemberStatus resource see the related issue.
Example:
```
apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: MemberStatus
metadata:
annotations:
toolchain.dev.openshift.com/last-applied-configuration: '{"metadata":{"name":"toolchain-member-status","namespace":"rsenthil-member-operator","creationTimestamp":null},"spec":{},"status":{"memberOperator":{"version":"","revision":"","buildTimestamp":" …
```
> Add member controller

- deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml
- deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml
- hack/deploy_csv.yaml
This PR contains generated files for the new Host field of the MemberStatus API that will be used to report the host connection status with toolchain Condition type instead of Kubefed types.
> Generated files for memberstatus Host field

- go.mod
- go.sum
- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
- test/memberstatus_assertion.go
Related PR: https://github.com/codeready-toolchain/toolchain-common/pull/118
This PR updates the member status controller to use the new memberStatus.Status.Host field which now uses Toolchain Conditions instead of Kubefed conditions. It also updates to use `ValidateComponentConditionReady` to get errors directly from the component conditions.
> Use new member status api for host connection and update component error handling

- go.mod
- go.sum
- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccount/useraccount_controller_test.go
- test/nstemplateset_assertion.go
* Uses DeepEqual instead of CompareTo when comparing NSTemplateSet spec object
* refactors some tests and adds a few more to cover cases when the only subpart of the NSTemplateSet is changed
depends on https://github.com/codeready-toolchain/api/pull/171
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/137
> fix(CRT-746): use DeepEqual instead of CompareTo for NSTemplateSet

- cmd/manager/main.go
This PR makes printing the config the same as what is done in the host-operator - https://github.com/codeready-toolchain/host-operator/blob/master/cmd/manager/main.go#L277-L289 
It removes "key": "key1", "value":"value1" and replaces with "key1":"value1"
> removing key/value prefix strings when logging

- cmd/manager/main.go
- deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml
- deploy/role.yaml
- hack/deploy_csv.yaml
add missing role on `services/finalizers`
E2E Tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/143
(similar to https://github.com/codeready-toolchain/host-operator/pull/262)
> fix: start metrics server at operator startup

- pkg/controller/nstemplateset/cluster_resources.go
- pkg/controller/nstemplateset/namespaces_test.go
- pkg/controller/nstemplateset/nstemplateset_controller_test.go
- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccountstatus/useraccount_status_controller.go
- pkg/controller/useraccountstatus/useraccount_status_controller_test.go
Reset to "0" the SyncIndex on the MasterUserRecord.
The MasterUserRecord Controller will react accordingly.
Also, smaller changes:
- reorder return parameters
- add logger to display more messages
- reword error message
- reorganize subtests in categories (success vs failure)
Updates https://issues.redhat.com/browse/CRT-778
> reset syncindex on MasterUserRecord when UserAccount is deleted

- deploy/env/e2e-tests.yaml
- go.mod
- go.sum
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
make MemberStatus requeue/refresh time configurable so we don't need to wait for the updates 5 seconds
> feat: make MemberStatus requeue/refresh time configurable

- cmd/manager/main.go
- pkg/controller/idler/idler_controller.go
- pkg/controller/idler/idler_controller_test.go
This is an implementation of the @MatousJobanek's idea of watching the Idler only and not watching pods at all. So, we could stop watching all namespaces for now.
TODO:
> Idler: don't watch all namespaces/pods

- cmd/manager/main.go
- pkg/controller/idler/idler_controller.go
- pkg/controller/idler/idler_controller_test.go
Unfortunately this solution doesn't work.
If we set the manager option to the specific namespace instead of "" (all namespaces) then it affects not only watchers but also `List()` in the client. It seems to return an empty list if we try to list from a different namespace.
We do use `Get()` in NSTemaplateSet controller which seems to be working with other namespaces. Not sure why `List()` works differently though.
It requires additional investigation. We also really have to add some e2e tests for the idler. It's impossible to test it properly in unit tests.
Until this is fixed properly I think we have to revert this.
> Revert "Idler: don't watch all namespaces/pods (#201)"

- cmd/manager/main.go
- pkg/controller/controller.go
- pkg/controller/idler/idler_controller.go
- pkg/controller/idler/idler_controller_test.go
- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/nstemplateset/nstemplateset_controller.go
- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccountstatus/useraccount_status_controller.go
This PR makes the client that watches all namespaces more generic. It's being passed to all controller as another client so it can be easily reached and used in MemberStatus controller. 
The PR also removes some unnecessary code.
> chore: make the client for all namespaces more generic

- go.mod
- go.sum
- pkg/apis/apis.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
- test/memberstatus_assertion.go
Retrieves the Console and Che routes and stores them in `MemberStatus`. This will be used in the host operator instead of directly retrieving them from the member cluster.
Most of the commits were taken from https://github.com/codeready-toolchain/member-operator/pull/208
Paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/185
> Routes in memberstatus

- cmd/manager/main.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
Adds code to retrieve member operator configuration from a secret. This works similar to the host operator.
Also added functions to retrieve the che admin username and password from the secret.
Related issue: https://issues.redhat.com/browse/CRT-845
> Add code to retrieve che credentials from a member operator secret

- cmd/manager/main.go
- go.mod
- pkg/che/che.go
- pkg/che/tokencache.go
- pkg/che/tokencache_test.go
- pkg/configuration/configuration.go
- pkg/rest/rest.go
- pkg/utils/route.go
Adds a Che client to the member operator that does the following:
- looks up the Che Keycloak server
- uses credentials from the member-operator-secret to request a token from Che's Keycloak server
- retrieves the token from the server and caches it
- reuses the cached token until it expires
More functions will be added to che.go in PRs to come. (eg. Find user and Delete user functions)
Related issue: https://issues.redhat.com/browse/CRT-846
> Add Che client with token cache

- .gitignore
- deploy/cluster_role.yaml
- deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml
- deploy/operator.yaml
- deploy/webhook/member-operator-webhook.yaml
- hack/deploy_csv.yaml
- make/go.mk
- make/test.mk
- pkg/apis/apis.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
This PR adds:
* mutating admission webhook template
* generation of the template into an asset
* necessary permissions for deploying objects form the template
* configuration to load the member-operator-webhook image location URL
This PR doesn't introduce any real logic yet - deployment of the template as well as the logic of the webhook will come in the next PR.
> feat: introduce webhook template & add permissions & configuration

- make/manifests.mk
use the `--component-image` param from https://github.com/codeready-toolchain/api/pull/205
> chore: use webhook image as component image

- cmd/manager/main.go
- go.mod
- go.sum
- pkg/che/che_test.go
- pkg/che/tokencache_test.go
- pkg/controller/useraccount/useraccount_controller_test.go
- pkg/webhook/deploy/cert/secret.go
by default, this function wants to use all out CRDs, but when we have a "host-only"
cluster, this metrics server fails to load the CRDs from etcd, which causes CrashLoops.
If we really need this metrics server, then we should taylor the list of CRDs to expose.
Keeping the `serveCRMetrics` for now, but with a comment to avoid linter issue,
since it's not used.
Also, address pending lint issues with fixes or comments
> disable CR metrics

- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccount/useraccount_controller_test.go
Fix for bug https://issues.redhat.com/browse/CRT-891
Update the Che user deletion logic such that if the UserExists check comes back with a 404 then we won't continue further to call the DELETE API, we'll assume the Che data has been removed and continue with deactivation/removal.
It also removes the logic to remove the setting of the special condition that was used for caching the cheUserID value between attempts. We no longer need to cache the cheUserID because if we can't get it due to a 404 then it now means the user is removed, if cannot get it due to another response code then it will be an error condition set on the useraccount.
> Proceed with removal if user not found

- deploy/crds/toolchain_v1alpha1_memberstatus_crd.yaml
- deploy/olm-catalog/toolchain-member-operator/manifests/toolchain_v1alpha1_memberstatus_crd.yaml
- go.mod
- go.sum
- hack/deploy_csv.yaml
- pkg/che/che.go
- pkg/che/che_test.go
- pkg/che/tokencache.go
- pkg/configuration/configuration.go
- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
- pkg/controller/useraccount/useraccount_controller.go
- pkg/controller/useraccount/useraccount_controller_test.go
- test/memberstatus_assertion.go
🚨  **IMPORTANT:** 🚨 
The user deletion enabled config variable must be set to true on the member operator config maps on staging and production *before* merging this PR:
```
che:
user_deletion_enabled: true
```
**Description:**
Adds a new section to the memberstatus specifically for any Che integrations.
**Detects the following problem conditions and exposes them as part of the member status:**
- che admin credentials not configured when Che user deletion is enabled
- che route not found
- unable to successfully access Che user API
**Additional changes:**
- adds a new config variable specifically for enabling/disabling the Che user deletion logic
**Example status:**
```
status:
che:
conditions:
- lastTransitionTime: "2020-12-18T00:35:55Z"
lastUpdatedTime: "2020-12-18T00:35:55Z"
message: …
```
> Che client status

- cmd/manager/main.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
By default the users' pods webhook will be deployed, however in some cases (eg. e2e tests) there can be multiple member operators installed in the same cluster. In those cases only 1 webhook is needed because the MutatingWebhookConfiguration is a cluster-scoped resource and naming can conflict.
This PR adds a new configuration option that can toggle whether or not the member operator will deploy the webhook and create the associated `MutatingWebhookConfiguration` resource as well. It will be used by the e2e test setup to disable the deployment of the users' pods webhook.
Related issue:
https://issues.redhat.com/browse/CRT-770
> Webhook deploy config

- pkg/controller/memberstatus/memberstatus_controller.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
Updates the member status error messages related to Che user deletion to make it a little more clear that they are occurring because Che user deletion is enabled.
With these changes the status looks like this:
```
status:
che:
conditions:
- lastTransitionTime: "2021-02-17T20:21:38Z"
lastUpdatedTime: "2021-02-17T20:21:38Z"
message: 'Che dashboard URL unavailable but che user deletion is enabled: Route.route.openshift.io
"codeready" not found'
reason: CheRouteUnavailable
status: "False"
type: Ready
conditions:
- lastTransitionTime: "2021-02-17T20:21:38Z"
lastUpdatedTime: "2021-02-17T20:21:38Z"
message: 'components not ready: [che]'
reason: ComponentsNotReady
status: "False"
type: Ready
...
```
> Update user deletion error msg to be more clear and helpful

- go.mod
- go.sum
- pkg/controller/nstemplateset/nstemplateset_controller.go
Related issue: https://issues.redhat.com/browse/CRT-941
As part of the split up of the cluster resource quotas there will be even more reconciles of the NSTemplateSet controller since it's watching for changes to cluster level resources. However, the controller is only really interested in changes to the spec so this PR adds a watch predicate for generation changes so that status changes will not trigger reconciles.
> Add predicate to ignore CRQ status changes

- .github/workflows/workflow.yml
- make/docker.mk
adds GH Actions workflow that releases a new version of member-operator on every commit to master
depends on https://github.com/codeready-toolchain/toolchain-cicd/pull/22
> chore: add GH Actions workflow for releasing new operator versions

- .github/workflows/workflow.yml
So, we install podman 3.0 instead of 3.1.0 which has a critical bug.
> Use ubuntu-18.04 in GH Actions

- cmd/manager/main.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/controller/memberstatus/creation_test.go
- pkg/controller/memberstatus/memberstatus_controller_test.go
No need for memberstatus name to be configurable, we'll just hardcode it to "toolchain-member-status"
> Use constant for member status name

- .github/workflows/publish-operator-for-e2e-tests.yml
This is a workflow that will publish bundle of member operator for every PR
This is needed for the migration to operator-sdk 1.8.0
Since it uses `pull_request_target` to be able to access secrets, I need to have it in master branch so it is executed by GH actions
> chore: add publish-operator-for-e2e-tests worflow

- .github/workflows/publish-operator-for-e2e-tests.yml
the same fix as in https://github.com/codeready-toolchain/host-operator/pull/467
plus it uses composite from https://github.com/MatousJobanek/toolchain-cicd/blob/master/publish-operator-for-e2e-tests/action.yml
> fix: checkout PR head & use composite action

- cmd/manager/main.go
- controllers/memberoperatorconfig/cache.go
- controllers/memberoperatorconfig/cache_test.go
- controllers/memberoperatorconfig/configuration.go
- controllers/memberoperatorconfig/configuration_test.go
- controllers/memberoperatorconfig/memberoperatorconfig_controller.go
- controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
- controllers/memberstatus/memberstatus_controller.go
- controllers/memberstatus/memberstatus_controller_test.go
- deploy/cluster_role.yaml
- deploy/olm-catalog/toolchain-member-operator/manifests/toolchain-member-operator.clusterserviceversion.yaml
- go.mod
- go.sum
- hack/deploy_csv.yaml
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
Implements a controller for memberoperatorconfig resources plus the cache and config helpers similar to what we have for toolchainconfig.
e2e test PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/324
> Memberoperatorconfig controller

- pkg/che/che_test.go
- pkg/che/tokencache_test.go
- pkg/utils/route/route.go
- pkg/utils/route/route_test.go
don't append path in the URL if contains only slash
> fix: don't append path if contains only slash

- controllers/memberoperatorconfig/cache.go
- controllers/memberoperatorconfig/cache_test.go
- controllers/memberoperatorconfig/memberoperatorconfig_controller.go
- controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
- controllers/memberstatus/memberstatus_controller.go
- controllers/memberstatus/memberstatus_controller_test.go
- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
- main.go
- pkg/che/che.go
- pkg/che/che_test.go
- pkg/che/tokencache_test.go
There is a problem on staging where the che user API check is failing:
```
che:
conditions:
- lastTransitionTime: "2021-07-19T15:43:47Z"
lastUpdatedTime: "2021-07-19T15:43:47Z"
message: 'che user API check failed: the che admin username and/or password
are not configured'
reason: CheUserAPICheckFailed
status: "False"
type: Ready
```
I believe this is occurring because when we moved to using the ToolchainConfig on the staging cluster we hadn't updated it to include all the latest configuration so the Che secret reference configuration was missing. The ToolchainConfig has since been updated and is now correct but the che user API check is still failing.
The current problem is that the che client was initialized in main.go (`che.InitDefaultCheClient(crtConfig, allNamespacesClient)` and …
> Che client should get config dynamically

- openshift-ci/Dockerfile.tools
oc and golang are already available as part of test configuration. Thus removing the downloading and installing of them from dockerfile.
> remove downloading and installing of golang and oc from dockerfile

- controllers/nstemplateset/nstemplateset_controller.go
- controllers/nstemplateset/nstemplateset_controller_test.go
stop reconciling if deletion is stuck because we don't want to reconcile over and over again every second for stuck deletions
> fix: stop reconciling if deletion is stuck

- .github/workflows/publish-operators-for-e2e-tests.yml
relies on https://github.com/codeready-toolchain/toolchain-cicd/pull/35
triggers the GH Actions workflow based on any of the retest comments.
However, this event won't update the status check in the PR - the reason is that PR is tied to a specific sha, but comment not.
> feat: trigger GH Actions workflow for retest comment

- controllers/nstemplateset/cluster_resources_test.go
- controllers/nstemplateset/namespaces_test.go
- controllers/nstemplateset/nstemplateset_controller_test.go
- controllers/nstemplateset/nstemplatetier.go
- controllers/nstemplateset/nstemplatetier_test.go
This PR sets a new param `MEMBER_OPERATOR_NAMESPACE` when applying templates. This param will be used by the appstudio tier to setup a role binding for the service account.
> Add member operator namespace to the tier params

- config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
- go.mod
- go.sum
- test/nstemplateset_assertion.go
- UserAccountController doesn't set owner reference between
the UserAccount and the NSTemplateSet
- UserAccountController deletes the NSTemplateSet
before removing the finalizer on the UserAccount resource, during its
deletion (until the Space Controller exists and takes care of it)
- If UserAccount.Spec.NSTemplateSet is empty, then UserAccountController
ignores the NSTemplateSet for all operations
See also:
- https://github.com/codeready-toolchain/api/pull/263
- https://github.com/codeready-toolchain/toolchain-common/pull/216
- https://github.com/codeready-toolchain/toolchain-e2e/pull/407
Fixes https://issues.redhat.com/browse/CRT-1305
> refactor: decouple UserAccounts from NSTemplateSets

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
We cannot create Identity in AppStudio stage cluster because we don't have claim override enabled there. Otherwise, it fails with: 
```
conditions:
- lastTransitionTime: "2021-12-13T14:35:13Z"
message: 'User.user.openshift.io "mjobanek" is invalid: identities[0]: Invalid
value: "DevSandbox:f:528d76ff-f708-43ed-8cd5-fe16f4fe0ce6:mjobanek": must
be in the format <providerName>:<providerUserName>'
reason: UnableToCreateUser
status: "False"
type: Ready
```
This PR skips the creation of `User` & `Identity` if the `tierName` equals to `appstudio`. It also deletes the `User` & `Identity` if it's already present.
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/424
> feat: if appstudio then don't create User nor Identity

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
delete the Identity & User resources only when it contains the "owner" label to unblock @alexeykazakov's broken account in AppStudio stage cluster :-)
is paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/428
> fix: delete identity & user only with owner label

- controllers/nstemplateset/cluster_resources.go
- controllers/nstemplateset/namespaces.go
- controllers/nstemplateset/nstemplatetier.go
- controllers/nstemplateset/nstemplatetier_test.go
With spaces, the `USERNAME` param gets confusing or inadequate.
> refactor: map for params when processing a template

- controllers/idler/idler_controller.go
- controllers/nstemplateset/space_roles.go
revert unneeded changes after gosec linter complains
use `// nolint:gosec` comment instead.
> chore: revert linter changes

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
- go.mod
- go.sum
This PR replaces the ad hoc code that sets Identity property values in the UserAccountController and uses the IdentityNamingStandard utility instead.
Fixes https://issues.redhat.com/browse/CRT-1421
> Updated UserAccountController to use IdentityNamingStandard

- controllers/useraccount/useraccount_controller.go
Fix for the following error reported by Chris Chase on RHODS cluster:
```
{"level":"error","ts":"2022-02-16T01:17:12.679Z","msg":"Observed a panic: \"assignment to entry in nil map\" (assignment to entry in nil map)\ngoroutine 1712 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic(0x196edc0, 0x1d78070)\n\t/tmp/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)\n\t/tmp/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x86\npanic(0x196edc0, 0x1d78070)\n\t/opt/hostedtoolcache/go/1.16.13/x64/src/runtime/panic.go:965 +0x1b9\ngithub.com/codeready-toolchain/member-operator/controllers/useraccount.addProviderLabel(0x1df2dc0, 0xc002b67500, 0x1de2718, 0xc0004fd090, 0x0, …
```
> Fix panic in useraccount controller

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
Unit tests for https://github.com/codeready-toolchain/member-operator/pull/337
After adding the unit test with a User/Identity that had nil labels the tests were failing because the assertUser function checks the following:
```
assert.Equal(t, userAcc.Name, user.Labels["toolchain.dev.openshift.com/owner"])
assert.Equal(t, toolchainv1alpha1.ProviderLabelValue, user.Labels[toolchainv1alpha1.ProviderLabelKey])
```
So I'm assuming it's always expected that both owner and provider labels should be present? At least that's the assumption I went with to make the unit tests pass. I changed the `addProviderLabel` func to `addOwnerAndProviderLabels` so it adds both. Please verify that that's what we actually want.
> Adjust logic and add unit test

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- main.go
- pkg/webhook/validatingwebhook/validate.go
- tools.go
Custom resources can use scale subresource to manage the replicas of deployments. In this case the idler needs to update the autoscalingv1.Scale resource in order to terminate the deployment (replicas=0).
Update the idler component to also support deployments managed by scale sub resources. In case a deployment is owned by a custom resource that holds a scale sub resource the idler will patch the scale resource instead of the deployment directly.
This makes sure that the idler is able to terminate deployments owned by scale resources, too.
At the moment this is being used by Camel K workloads such as Integration and KameletBinding custom resources.
Fixes #343
> fix(#343): Add support for scale subresource

- config/rbac/camel_k_role.yaml
- config/rbac/camel_k_role_binding.yaml
- config/rbac/kustomization.yaml
Allow controller manager to scale Camel K Integration and KameletBinding custom resources on the cluster
Signed-off-by: Christoph Deppisch <cdeppisch@redhat.com>
> fix(#343): Add permissions to scale Camel K resources

- make/docker.mk
- make/go.mk
- make/manifests.mk
While building docker images on Mac M1 chipset and deploying to AWS dev environment (running on linux/amd64) I need to change the build platform from my default one.
This PR enables configuring the docker build platform option, example command to run from within the toolchain-e2e dir:
make dev-deploy-e2e HOST_REPO_PATH=$(PWD)/../host-operator goarch=amd64 IMAGE_BUILDER=docker
NOTE: doesn't work with podman on Apple M1 apparently, the images starting with FROM scratch are not being built for the architecture specified with --platform option but with the default one (in my case arm64 ). This could be an issue with podman on Mac only, since docker works fine.
> enable cross-platform build

- controllers/nstemplateset/nstemplateset_controller.go
- controllers/useraccount/useraccount_controller.go
to improve reading the logs so there are no error lines like:
```
{"level":"error","ts":"2022-12-05T14:27:28.014Z","msg":"failed to get NSTemplateSet","controller":"nstemplateset","controllerGroup":"toolchain.dev.openshift.com","controllerKind":"NSTemplateSet","nSTemplateSet":{"name":"migration-second-member-provisioned-user"},"namespace":"","name":"migration-second-member-provisioned-user","reconcileID":"de26c1ee-ef9e-4bbb-bbd3-387e2069e2a1","error":"NSTemplateSet.toolchain.dev.openshift.com \"migration-second-member-provisioned-user\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controll …
```
> use info when NSTemplateSet/UserAccount is not found

- make/manifests.mk
save `kustomize build` output to temporary file, in order to intercept failures and avoid publishing empty bundles.
See "green job" with failed build example:
https://github.com/codeready-toolchain/member-operator/actions/runs/3749944798/jobs/6369029675#step:9:1296
> handle kustomize build failure

- go.mod
- go.sum
This PR is for testing new toolchaincluster controller changes that adds home label on toolchaincluster of type member.
See Jira: https://issues.redhat.com/browse/ASC-245
Related PRs:
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/284
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/722
> test new toolchaincluster controller

- controllers/nstemplateset/nstemplatetier_test.go
address the `loop variable tierTemplate captured by func literal` warning
> test: use var within loop

- config/rbac/kustomization.yaml
- config/rbac/regsvc_proxy_lister_role.yaml
- config/rbac/regsvc_proxy_lister_rolebinding.yaml
Creates the ClusterRole that's required for API discovery to work when users use the Proxy Space Lister API.
See https://github.com/codeready-toolchain/api/pull/337 and https://github.com/codeready-toolchain/registration-service/pull/301
> Create ClusterRole for the proxy workspace lister API

- config/crd/bases/toolchain.dev.openshift.com_nstemplatesets.yaml
- controllers/nstemplateset/namespaces.go
- controllers/nstemplateset/nstemplateset_controller.go
- controllers/nstemplateset/nstemplateset_controller_test.go
- controllers/nstemplateset/status.go
- controllers/nstemplateset/status_test.go
- go.mod
- go.sum
- test/nstemplateset_assertion.go
This PR adds the NSTemplateSet.Status.ProvisionedNamespaces field, which will contain all the namespace names provisioned by the NSTemplateSet.
The Namespace.Type field it's still WIP, at the moment only the first namespace in alphabetical order will have this field set to default, further work will be needed once we have better requirements about how many type of namespaces we need to support.
Jira Story: https://issues.redhat.com/browse/ASC-252  
Only first two acceptance criteria are covered by this set of PRs, there will be separate PRs for the update to the Space Controller.
Related PRs:
- api: https://github.com/codeready-toolchain/api/pull/338
Paired with:
- e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/660
> feat: add list of provisioned namespaces into NSTemplateSet status

- controllers/nstemplateset/namespaces.go
the sorted namespaces list was saved to `sortedNamespaces`, but apparently it was unused as discussed in this [PR](https://github.com/codeready-toolchain/member-operator/pull/407)
> fix: sort namespace list logic

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
- go.mod
- go.sum
Propagate both the UserID and AccountID annotation values from `UserAccount` to `User` during reconciliation, if both values are set.  If the values are not set then delete the annotations on the `User`.
Fixes https://issues.redhat.com/browse/CRT-1718
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/670
> Set UserID and AccountID in User resource if they are set in UserAccount

- build/Dockerfile.consoleplugin
- cmd/consoleplugin/main.go
- deploy/consoleplugin/member-operator-console-plugin.yaml
- make/docker.mk
- make/go.mk
- pkg/consoleplugin/deploy/deployment.go
- pkg/consoleplugin/deploy/deployment_test.go
This PR introduces an empty service which will be used to return Web Console Plugins, such as pendo.
This PR:
- Adds all needed wiring to make target to build an image for the service
- Adds all service manifests
- Adds a new package and a function to deploy the service
Next steps:
- Add Console Plugin specific configuration to MemberOperatorConfig:
- Deploy the service: true/false
- Pendo key
- Implement the health endpoint in the service
- Start deploying the service in the member operator config controller. Similar to https://github.com/codeready-toolchain/member-operator/blob/master/controllers/memberoperatorconfig/memberoperatorconfig_controller.go#L91
- Implement the endpoint which will return the plugin JS.
> Web Console plugin service skeleton

- deploy/consoleplugin/member-operator-console-plugin.yaml
- pkg/consoleplugin/deploy/deployment_test.go
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/710
> use complete provider label key in plugin manifests

- controllers/nstemplateset/cluster_resources.go
- controllers/nstemplateset/cluster_resources_test.go
- controllers/nstemplateset/namespaces.go
- controllers/nstemplateset/namespaces_test.go
- controllers/nstemplateset/nstemplateset_controller.go
- controllers/nstemplateset/nstemplateset_controller_test.go
- controllers/nstemplateset/nstemplatetier_test.go
- controllers/nstemplateset/space_roles.go
- controllers/nstemplateset/status_test.go
This is part of the work to revisit/rename the parameters in the NSTemplateTier templates.
Jira: https://issues.redhat.com/browse/CRT-1766
This is third and last PR for renaming USERNAME parameter into SPACE_NAME.
List of all PRs required for the renaming process: 
member-operator - Introduce the usage of the new parameter SPACE_NAME along with the existing one USERNAME (merged see https://github.com/codeready-toolchain/member-operator/pull/432)
host-operator -  Rename USERNAME with SPACE_NAME (merged see https://github.com/codeready-toolchain/host-operator/pull/801)
member-operator - (current one) Remove/replace usage of USERNAME in favor of SPACE_NAME
As mentioned, this PR is for 3rd point.
> fix: rename USERNAME template parameter with SPACE_NAME 

- config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
The name is conflicting with the SCC created by OSP, and triggered the RHTAPBUGS-304 issue.
This PR prepares the migration to the new SCC name. Another PR will be submitted to deprecate the old name once the new SCC is deployed on all environments.
> Rename pipelines-scc to appstudio-pipelines-scc 1/2

- config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
The name is conflicting with the SCC created by OSP, and triggered the RHTAPBUGS-304 issue.
This PR deprecates the old SCC name.
> Rename pipelines-scc to appstudio-pipelines-scc 2/2

- controllers/nstemplateset/client_test.go
- controllers/nstemplateset/cluster_resources.go
- controllers/nstemplateset/cluster_resources_test.go
- controllers/nstemplateset/namespaces.go
- controllers/nstemplateset/namespaces_test.go
- controllers/nstemplateset/nstemplateset_controller_test.go
- controllers/nstemplateset/space_roles.go
- controllers/nstemplateset/space_roles_test.go
- test/namespace_assertion.go
Drop OwnerLabelKey in favor of the newly introduced SpaceLabelKey
Part of Jira: https://issues.redhat.com/browse/SANDBOX-51
Paired with:
- e2e : https://github.com/codeready-toolchain/toolchain-e2e/pull/747
> fix: drop toolchainv1alpha1.OwnerLabelKey label

- controllers/memberstatus/memberstatus_controller.go
- controllers/memberstatus/memberstatus_controller_test.go
Move member operator version is up to date check to "All components ready test" 
See discussion in previous PR: https://github.com/codeready-toolchain/member-operator/pull/446#discussion_r1255544115
> fix: move member operator unit test for revision check to All components ready test

- controllers/nstemplateset/client.go
- controllers/nstemplateset/client_test.go
paired PR https://github.com/codeready-toolchain/toolchain-e2e/pull/767
> directly create SA if does not already exist

- make/go.mk
- pkg/webhook/deploy/deployment.go
`go vet ./...` seems to be broken.
```
❯ go vet ./...
pkg/webhook/deploy/deployment.go:7:2: "github.com/codeready-toolchain/member-operator/pkg/webhook/deploy/webhooks" imported and not used
pkg/webhook/deploy/deployment.go:49:21: undefined: templates
vet: pkg/webhook/deploy/deployment.go:49:21: undefined: templates
```
As the folder containing the generated code is named `webhooks`, I changed the pkg name from `templates` to `webhooks`.
> fix: go vet

- config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml
- go.mod
- go.sum
generated files from https://github.com/codeready-toolchain/api/pull/378
> fix: add missing binding request field

- cmd/webhook/main.go
> webhooks: disable HTTP/2

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
If the Pod is in complete state and doesn't have a controller, no notification should be sent to the user.
This relates to #478
> No Notification for "Completed" and without controller Pods

- make/test.mk
The code was getting the toolchain-e2e branch name ok but using the wrong variable to fetch it.
> complete bad fix

- controllers/memberoperatorconfig/memberoperatorconfig_controller.go
- controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
- make/test.mk
- pkg/webhook/mutatingwebhook/mutate.go
- pkg/webhook/mutatingwebhook/mutate_test.go
- pkg/webhook/mutatingwebhook/userpods_mutate.go
- pkg/webhook/mutatingwebhook/userpods_mutate_test.go
- pkg/webhook/mutatingwebhook/vm_mutate.go
- pkg/webhook/mutatingwebhook/vm_mutate_test.go
https://issues.redhat.com/browse/SANDBOX-363
- Adds logic to parse userData for both cloudInitNoCloud and cloudInitConfigDrive volumes and update the data
- Refactored and simplified the unit tests for mutating webhooks
- Temporarily hardcoding a fake key, will have a separate PR for retrieval from config
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/830
> Update VM webhook to add cloud init user data

- config/manager/manager.yaml
> disable HTTP/2 on kube-rbac-proxy container

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
> fix: forward context in useraccount reconciler

- config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml
For api change in  https://github.com/codeready-toolchain/api/pull/386
> add disable inheritance api

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
This PR is a total refactor of the UserAccountController to use the values stored in PropagatedClaims instead of any other property or annotation values that are derived from the user's SSO token.
Fixes https://issues.redhat.com/browse/SANDBOX-431
E2E tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/858
> refactored member operator to only use properties from propagated claims

- controllers/useraccount/useraccount_controller.go
- controllers/useraccount/useraccount_controller_test.go
Minor addition to previous refactoring of UserAccountController to use the Email property from PropagatedClaims instead of the `email` annotation.
> Don't use email annotation, use PropagatedClaims instead

- go.mod
- go.sum
Updating the APi Dependencies
This is to Drop unused parameters from the embedded MUR.Status.UserAccounts.Clusters type
Related PRs
API - https://github.com/codeready-toolchain/api/pull/387
> Updating the APi Dependencies for Drop unused parameters

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/943
> update to use email from propagated claims

- config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
This removes the ability for TaskRuns to modify themselves. This was previously used by the JVM build service but should no longer be nessesary.
> RHTAPBUGS-1070 tasks can overwrite others

- config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
In order to create ephemeral namespaces for
testing konflux components, the appstudio-pipeline
service account needs to be able to manage (create, delete, get) the SpaceRequest custom resource.
~Related PR:  https://github.com/redhat-appstudio/infra-deployments/pull/3203~
> chore(RHTAPWATCH-765): appstudio-pipeline can manage SpaceRequests

- config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
The appstudio-pipelines-runner needs watch/list/delete permissions for spacerequests.
> chore: grant pipelines-runner additional spacerequest permissions

- pkg/webhook/mutatingwebhook/vm_mutate.go
- pkg/webhook/mutatingwebhook/vm_mutate_test.go
When `vm:spec:template:spec:domain:memory:guest` is set then use its value as the limit.
> Handle when domain memory request is set

- pkg/webhook/mutatingwebhook/vm_mutate.go
- pkg/webhook/mutatingwebhook/vm_mutate_test.go
https://issues.redhat.com/browse/SANDBOX-499
Updates the member webhook to ensure the sandbox toleration is set on VM resources so that the VM can be scheduled on the BM node.
```
tolerations:
- effect: NoSchedule
key: sandbox-cnv
operator: Exists
```
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/898
> Ensure sandbox toleration

- go.mod
- go.sum
I need to test changes in https://github.com/codeready-toolchain/toolchain-e2e/pull/907 so while doing that I decided to update api & toolchain-common dependencies so I have some meaningful changes in the PR :-) 
The dependency updates doesn't relate to the changes in toolchain-e2e anyhow.
> update api & test changes in e2e setup

- .github/workflows/publish-operators-for-e2e-tests.yml
my bad, I thought '@v2' would work, but it does not: https://github.com/codeready-toolchain/member-operator/actions/runs/8157751678/job/22298124082\?pr\=539
> fix octokit/request-action version

- deploy/toolchaincluster/member-sa.yaml
This PR adds only the manifests for the member toolchaincluster SA, ClusterRole and ClusterRoleBinding. The functionality for applying the manifests in the cluster will be implemented in follow up PRs.
For now there's a common functionality that parses those manifests from `embed.FS` filesystem.
https://github.com/codeready-toolchain/toolchain-common/pull/365
Those resources are now applied by the `add-cluster.sh` script, see: https://github.com/codeready-toolchain/toolchain-cicd/blob/34ea85fe21ae05c9bb1a0a2bbdc986b94c8d9e92/scripts/add-cluster.sh#L36
Jira: https://issues.redhat.com/browse/KSPACE-7
Related PRs:
common: https://github.com/codeready-toolchain/toolchain-common/pull/365
host-operator: https://github.com/codeready-toolchain/host-operator/pull/974
> Create templates with member ToolchainCluster-related manifests

- go.mod
- go.sum
- main.go
- test/cluster.go
This is related to Drop the distinction between host & member ToolchainClusters
Related PRs:
Toolchain-Common - https://github.com/codeready-toolchain/toolchain-common/pull/359
Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/971
Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/402
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/893
Sandbox-sre - https://github.com/codeready-toolchain/sandbox-sre/pull/1524
> KSPACE-20: Drop the distinction between host & member ToolchainClusters

- go.mod
- go.sum
- main.go
This is to convert the health-check goroutine into ToolchainCluster controller
The related PRs:
- Toolchain-Common - https://github.com/codeready-toolchain/toolchain-common/pull/386
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1010
The Other PRs where only Toolchain common dependency is updated 
- Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/949
- Registration-service - https://github.com/codeready-toolchain/registration-service/pull/422
- Sandbox-sre - https://github.com/codeready-toolchain/sandbox-sre/pull/1698
> KUBESAW-12: Convert the health-check goroutine into ToolchainCluster controller

- config/crd/bases/toolchain.dev.openshift.com_memberstatuses.yaml
- config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
This is related to https://github.com/codeready-toolchain/host-operator/pull/1017#issuecomment-2082716929 . Making the LastProbeTime optional first
> KUBESAW43: Make LastProbeTime optional

- config/crd/bases/toolchain.dev.openshift.com_memberstatuses.yaml
- config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
- go.mod
- go.sum
- test/cluster.go
This is to replace the special ToolchainClusterCondition with the standard toolchain Condition
This is Related to Change in
- API - https://github.com/codeready-toolchain/api/pull/416
- Toolchain-Common - https://github.com/codeready-toolchain/toolchain-common/pull/391
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1017
- Toolchain-E2E - https://github.com/codeready-toolchain/toolchain-e2e/pull/955
- KSCTL - https://github.com/kubesaw/ksctl/pull/38
Only change is updating the dependency of API and toolchain-common
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/424
- Sandbox-SRE - https://github.com/codeready-toolchain/sandbox-sre/pull/1706
> KUBESAW-43: Replace the special ToolchainClusterCondition with the standard toolchain Condition

- go.mod
- go.sum
Upgrade to toolchain-common with ToolchainController that no longer migrates the secrets to be labeled. Ths is now assumed.
This brings in PR https://github.com/codeready-toolchain/toolchain-common/pull/400.
Related PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1039
> Upgrade to the latest toolchain-common

- go.mod
- go.sum
[KUBESAW-121](https://issues.redhat.com/browse/KUBESAW-121)
depends on https://github.com/codeready-toolchain/toolchain-common/pull/403
require this PR to be merged first https://github.com/codeready-toolchain/toolchain-e2e/pull/994 as the required changes in toolchain-e2e are the same for host as well as for member
> fix: don't rely on certificates in ToolchainClusters

- go.mod
- go.sum
Issue: https://issues.redhat.com/browse/KUBESAW-134
Associated PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/1003
This brings the new version of the ToolchainCluster controller to the member operator, too.
> Migrate toolchain cluster secrets to contain kubeconfig for cluster connection

- config/crd/bases/toolchain.dev.openshift.com_memberstatuses.yaml
- config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
- go.mod
- go.sum
This trivially just updates the API and gets the updated CRD definitions.
Associated PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1056
- api: https://github.com/codeready-toolchain/api/pull/433
> Receive the updates from the API repo for the new fields in the ToolchainCluster status

- config/crd/bases/toolchain.dev.openshift.com_memberoperatorconfigs.yaml
> remove webConsolePlugin from ToolchainClusterConfig (phase 1)

- cmd/webhook/main.go
Member-operator was spamming this message in its logs, but there was no `err` field set.  Check that an error actually exists before logging it.
> silence member config logs when there's no error

- deploy/autoscaler/member-operator-autoscaler.yaml
- pkg/autoscaler/autoscaler_test.go
It's actually not a good idea to set both limits and requests to the same value for our autoscaler buffer.
There are three `Quality of Service Classes (QoS)` in Kube:
- Guaranteed
- Burstable
- BestEffort
The Pod has the `Guaranteed` QoS if:
- Every Container in the Pod must have a memory limit and a memory request.
- For every Container in the Pod, the memory limit must equal the memory request.
- Every Container in the Pod must have a CPU limit and a CPU request.
- For every Container in the Pod, the CPU limit must equal the CPU request.
The `Guaranteed` pods are evicted last if there is memory pressure in the node. But removing the limits and keeping the requests only we move the Autoscaler Buffer to the `Burstable` QoS. Same `QoS` as most user pods (some of the user pods can be …
> Don't set limits for Autoscaler Buffer

- go.mod
- go.sum
Update to the latest toolchain-common to read the connection details from the kubeconfig in TC secret.
Related PRs:
* toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/1046
> Update to the latest toolchain-common

- config/manager/manager.yaml
Have a unique label instead of default controller-manger, so that it becomes easier to perform operations to only our operators
this is a predecessor for PR 
KSCTL - https://github.com/kubesaw/ksctl/pull/79 
Similar PR 
Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1087
> KUBESAW-187: Have a unique label for our operators

- config/crd/bases/toolchain.dev.openshift.com_nstemplatesets.yaml
Generated by : https://github.com/codeready-toolchain/api/pull/445
Jira: https://issues.redhat.com/browse/KUBESAW-137
> feat: Update NSTemplateSet CRD

- make/go.mk
Introduce a make command for pre-requisite of verify-replace script
Related PRs:
Toolchain-common - https://github.com/codeready-toolchain/toolchain-common/pull/429 
Host Operator - https://github.com/codeready-toolchain/host-operator/pull/1091
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1049
Registration service - https://github.com/codeready-toolchain/registration-service/pull/465
Ksctl - https://github.com/kubesaw/ksctl/pull/81
> KUBESAW-192: Introduce a make command for pre-requisite of verify-replace

- cmd/webhook/main.go
This avoid the need of restarting the webhook when the certificate is rotated
> webhook: load TLS certificate at runtime

- .github/workflows/ci-golang-sbom.yml
- controllers/memberstatus/memberstatus_controller_test.go
- controllers/nstemplateset/space_roles.go
- pkg/webhook/mutatingwebhook/mutate.go
- pkg/webhook/validatingwebhook/validate_rolebinding_request.go
- pkg/webhook/validatingwebhook/validate_spacebindingrequest.go
- pkg/webhook/validatingwebhook/validate_ssp_request.go
- pkg/webhook/validatingwebhook/validate_vm_request.go
Updating the GolangciLint to v1.63.1 across all repos fix the linter error which were caught as a result of upgrading the linter
Similar PRs
- API - https://github.com/codeready-toolchain/api/pull/454
- Toolchain-common - https://github.com/codeready-toolchain/toolchain-common/pull/442
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1116
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/491
- Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1092
- Ksctl - https://github.com/kubesaw/ksctl/pull/97
> KUBESAW-250: Updating GolangCiLint to v1.63.1

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- test/idler_assertion.go
fixes https://issues.redhat.com/browse/SANDBOX-942
updated e2e test: https://github.com/codeready-toolchain/toolchain-e2e/pull/1096
> Fix DeploymentConfig idling

- controllers/useraccount/console_usersettings.go
- controllers/useraccount/console_usersettings_test.go
- controllers/useraccount/useraccount_controller_test.go
Since labels were never added by console and ownerReferences have now been added back in 4.17 - we can delete the logic to delete console setting resources using labels.
Will keep the part of deleting console setting resources using name for a while before deleting.
slack thread for reference - https://redhat-internal.slack.com/archives/CHK0J6HT6/p1738683125581909
> remove logic of deletion of console setting resources using label

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- controllers/idler/mapper.go
- controllers/idler/mapper_test.go
- controllers/idler/predicate.go
- controllers/idler/predicate_test.go
- main.go
- pkg/webhook/mutatingwebhook/userpods_mutate.go
Added watcher on pods with a predicate that should trigger the reconcile only if:
* pod exists in users namespace
* either the startTime was set in the pod's status, or it reached the restart threshold.
two fixes of scheduling the next requeue of the idler controller:
1. drops the `RequeueTimeThreshold` - the original value caused that the controller kept reconciling as crazy in instances with a high number of users 
2. take into account that VMs should live only one twelfth of the idler timeout - the next requeue should be scheduled accordingly.
> fix requeue in idler controller

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
:man_facepalming: 
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x194e580]
goroutine 593 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x1d9d220?, 0x34e8b00?})
/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x21f
github.com/codeready-toolchain/member-operator/controllers/idler.(*Reconciler).ensureIdling(0xc00063aba0, {0x23e6d60, 0xc010c2af90}, 0xc010c00c80)
/home/runner/work/member-operator/member-operator/controllers/idler/idler_controller.g …
```
> check that startTime is not nil

- main.go
@rajivnathan noticed that we have duplicated cached all-namespaces scoped clients. This PR removes one of them to decrease the memory utilization.
> do not duplicate cached clients

- deploy/autoscaler/member-operator-autoscaler.yaml
- pkg/autoscaler/autoscaler_test.go
gcr.io registry is gettig shutdown. The last day it will be available for pulls is March 20. See https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation
This PR is switching to the kube image registry instead.
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/1136
> Update the autoscaler-buffer image registry

- controllers/idler/idler_controller.go
the member-operator is missing AAP permissions
```
ansibleautomationplatforms.aap.ansible.com is forbidden: User \"system:serviceaccount:toolchain-member-operator:member-operator-controller-manager\" cannot list resource \"ansibleautomationplatforms\" in API group \"aap.ansible.com\" in the namespace
```
> fix(idler): missing AAP permissions

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
use patch instead of update when scaling down controllers to avoid conflicts https://redhat-internal.slack.com/archives/C064SKK3C2E/p1742656300541629?thread_ts=1742645702.696489&cid=C064SKK3C2E
> idler: patch instead of update

- cmd/main.go
- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- go.mod
- Resolves the issue with the DynamicClient and the VM stop subresource API that caused the error below
- Removes the rest client from the idler for simplification. We can just use and manage 1 client instead of 2
- The code comments include specific details about the fix.
The error that was preventing use of the DynamicClient with the VM stop API:
{"level":"error","ts":"2025-03-19T14:37:10.179Z","msg":"Reconciler error","controller":"idler","controllerGroup":"toolchain.dev.openshift.com","controllerKind":"Idler","Idler":{"name":"user1-dev"},"namespace":"","name":"user1-dev","reconcileID":"b2be7e32-8c39-459d-9eeb-be94e2d49f80","error":"failed to ensure idling 'user1-dev': 406: Not Acceptable\n\nAvailable representations:","errorVerbose":"406: Not Acceptable\n\nAvailable …
> Fix dynamic client for idler

- cmd/main.go
- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
This reverts commit edd26db8a34ba159e336139014f22706e04f66d8.
Reverting the original PR instead and just keeping the REST client since the VM stop API doesn't seem to be made for the dynamic client
discussion thread https://redhat-internal.slack.com/archives/CHK0J6HT6/p1743092974483949
> Revert "Fix dynamic client for idler (#655)"

- controllers/idler/aap_idler.go
- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- test/idler_assertion.go
* collect errors when trying to idle pods and do not return them immediately - try to idle (and track) the other pods
* align the import aliases
* drop `github.com/pkg/errors`
related to this https://redhat-internal.slack.com/archives/C064SKK3C2E/p1742656916819689?thread_ts=1742645702.696489&cid=C064SKK3C2E
> idler: improve error handling

- .github/workflows/ci-golang-sbom.yml
- .golangci.yml
- controllers/idler/aap_idler_test.go
- controllers/idler/idler_controller_test.go
- controllers/memberstatus/memberstatus_controller_test.go
- controllers/nstemplateset/namespaces.go
- controllers/nstemplateset/namespaces_test.go
- controllers/nstemplateset/nstemplateset_controller_test.go
- pkg/klog/writer.go
- pkg/webhook/mutatingwebhook/mutate_test.go
- test/nstemplateset_assertion.go
upgraded `.golangci.yml` with `golangci-lint migrate`
include fixes suggested by `golangci-lint run -c ./.golangci.yml`
> chore(build): migrate to golangci-lint@v2 and golangci-lint-action@v7

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- controllers/idler/owners_test.go
a follow-up of https://redhat-internal.slack.com/archives/C064SKK3C2E/p1747301942697849 
two changes introduced:
1. ignores when there is an error returned when fetching the owners
2. moves & improves failure tests to owners_test.go file
> ignore errors when fething owners & improve tests

- cmd/main.go
- controllers/nstemplateset/client.go
- controllers/nstemplateset/client_test.go
- controllers/nstemplateset/cluster_resources.go
- controllers/nstemplateset/namespaces.go
- controllers/nstemplateset/namespaces_test.go
- controllers/nstemplateset/nstemplateset_controller_test.go
- controllers/nstemplateset/nstemplatetier.go
- controllers/nstemplateset/nstemplatetier_test.go
- controllers/nstemplateset/space_roles.go
- controllers/nstemplateset/tier_template_revision.go
- controllers/nstemplateset/tier_template_revision_test.go
- pkg/host/client.go
- pkg/host/client_test.go
- test/cluster.go
- test/nstemplateset_assertion.go
After the latest changes introduced in this PR: https://github.com/codeready-toolchain/member-operator/pull/666 the code always tries to get TTR first
https://github.com/codeready-toolchain/member-operator/blob/7a97fe7eb68d072f4af61a9eaaadb66ff289270a/controllers/nstemplateset/nstemplatetier.go#L36
but none TTR CR is currently present in the prod cluster, which means that the TierTemplate cache doesn't have any impact on the number of request made for TTRs. 
Since the call uses a client without a cache, then it always makes a request to the public api of the host cluster which may increase networking load on both sides (host & member).
This PR:
* introduced cached host cluster client that uses controller-runtime client backed by informer cache
* drops the TierTemplate cache
additional …
> replace TierTemplate cache with cached host cluster client

- config/manager/health_service.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
for probing via Blackbox Exporter
see also https://github.com/codeready-toolchain/host-operator/pull/1178
> monitoring: service to access '/healthz' endpoint

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- controllers/idler/owners.go
- controllers/idler/owners_test.go
- test/idler_assertion.go
a few refactoring changes:
* stop using all-namespaces client for owners - use DynamicClient only to support generic approach
* move controller/owner idling logic to owners.go to spread the code and decrease the size of the idler_controller.go file (the same applies to the tests)
* replace the duplicated scaling/deleting logic with generic functions `scaleToZero` and `deleteResource`.
> move owner idling to owners.go

- controllers/idler/idler_controller.go
- controllers/idler/idler_controller_test.go
- controllers/idler/owners.go
- controllers/idler/owners_test.go
a generic workaround for the broken AAP-internal idler: https://redhat-internal.slack.com/archives/C07UWTB1BPB/p1751090482552999
if idling of the top known owner either fails or the pod is running longer than 105% of the idler timeout (which means that the first idling didn't have any effect), then idle the second known owner.
Also, if there is a running pod that exceeded the timeout (which means that the idler tried to idle it) it schedules the next reconcile in the 5% of the timeout.
Assisted-by: Cursor (but this time it wasn't really helpful)
> idler second known owner if idling the first one didn't work
